Repository MatthewBeaulieu0/341-Website, pull requests merged in 2022-03, with the labels that each got.

#59 Backend Product Controller Testing.
  turboapp/apps/backend/package-lock.json
  turboapp/apps/backend/package.json
  turboapp/apps/backend/src/controllers/product_controller.ts
  turboapp/apps/backend/test/test_controllers/test_product.ts
Labels: documentation

#68 Checkout
  turboapp/apps/backend/src/controllers/user_controllers.ts
  turboapp/apps/backend/src/routes/user_routes.ts
  turboapp/apps/backend/src/services/order_services.ts
  turboapp/apps/backend/src/services/orderstatus_services.ts
  turboapp/apps/backend/src/services/product_services.ts
  turboapp/apps/backend/src/services/user_services.ts
  turboapp/package-lock.json
Labels: enhancement

#77 Product page fix
  turboapp/apps/web/src/app/components/featured-items/featured-items.component.ts
  turboapp/apps/web/src/app/components/pages/productpage/productpage.component.ts
  turboapp/apps/web/src/app/services/products.service.ts
Labels: bug

#84 Fixed bug with multiple emails.
  turboapp/apps/backend/src/controllers/user_controllers.ts
Labels: bug

#86 Implement an array of links for the product images in the backend
  setup/DatabaseCreationCode.sql
  setup/InsertionDatabase.sql
  turboapp/apps/backend/src/controllers/product_controller.ts
  turboapp/apps/backend/test/test_controllers/test_product.ts
  turboapp/apps/web/src/app/components/pages/productpage/productpage.component.html
  turboapp/apps/web/src/app/components/pages/productpage/productpage.component.ts
  turboapp/apps/web/src/app/models/product.ts
  turboapp/apps/web/src/assets/images/banana1.jpeg
  turboapp/apps/web/src/assets/images/banana2.jpeg
  turboapp/apps/web/src/assets/images/banana3.jpeg
  turboapp/apps/web/src/assets/images/bookshelf1.jpeg
  turboapp/apps/web/src/assets/images/bookshelf2.jpeg
  turboapp/apps/web/src/assets/images/bookshelf3.jpeg
  turboapp/apps/web/src/assets/images/calculator1.jpeg
  turboapp/apps/web/src/assets/images/calculator2.jpeg
  turboapp/apps/web/src/assets/images/calculator3.jpeg
  turboapp/apps/web/src/assets/images/chocolate1.jpeg
  turboapp/apps/web/src/assets/images/chocolate2.jpeg
  turboapp/apps/web/src/assets/images/chocolate3.jpeg
  turboapp/apps/web/src/assets/images/phone1.jpeg
  turboapp/apps/web/src/assets/images/phone2.jpeg
  turboapp/apps/web/src/assets/images/phone3.jpeg
  turboapp/apps/web/src/assets/images/strawberry1.jpg
  turboapp/apps/web/src/assets/images/strawberry2.jpg
  turboapp/apps/web/src/assets/images/strawberry3.jpeg
Labels: enhancement
